/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airline_project;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nitin
 */
public class LoginForm extends javax.swing.JFrame {
    boolean hide=true;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Air Sewa Login");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(612, 408));
        setMinimumSize(new java.awt.Dimension(612, 408));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel4.setText("Welcome to Air Seva");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 10, 350, 48);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,100));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 50, 90, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 110, 90, 25);
        jPanel1.add(username);
        username.setBounds(131, 42, 320, 30);

        jButton1.setText("H");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 140, 40, 23);
        jPanel1.add(password);
        password.setBounds(130, 100, 320, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 110, 470, 200);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Login");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 60, 80, 32);

        login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(140, 320, 75, 27);

        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("Cancel");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(400, 320, 80, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Airplane.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
//           this.setVisible(false);
//            Main obj=new Main();
//            obj.setVisible(true);
        try {
            // TODO add your handling code here:
        
            String UserName=username.getText();
            String Password=String.valueOf(password.getPassword());
            Connection con;//storing connection between database and code
            PreparedStatement pre;//prepare some queries that we are going to run in sql server
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/airline_project","root","J1a2y3d4e5n6#");
            pre=con.prepareStatement("select * from admin where Username=?");
            pre.setString(1,UserName);
            ResultSet rs=pre.executeQuery();
            if(rs.next()!=false)
            {
                byte[] salt=Base64.getDecoder().decode(rs.getString("Salt"));
                String HashCode=generateHash(Password,"MD5",salt);
                System.out.println(HashCode);
                if(rs.getString("Password").equals(HashCode))
                {
                    this.setVisible(false);
                    Main obj=new Main();
                    obj.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Wrong Password");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"No such username found");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_loginActionPerformed
    private String generateHash(String data,String algorithm,byte[] salt) throws NoSuchAlgorithmException
    {
        MessageDigest digest=MessageDigest.getInstance(algorithm);
        digest.reset();
        digest.update(salt);
        byte[] hash=digest.digest(data.getBytes());
        return bytesToStringHex(hash);
    }
    private final char[] hexArray="0123456789ABCDEF".toCharArray();
    private String bytesToStringHex(byte[] bytes)
    {
        char[] hexChars=new char[bytes.length*2];
        for(int j=0;j<bytes.length;j++)
        {
            int v=bytes[j]&0xFF;
            hexChars[j*2]=hexArray[v >>> 4];
            hexChars[j*2+1]=hexArray[v & 0x0F];
        }
        return new String(hexChars);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(hide==false)
        {
            jButton1.setText("H");
            password.setEchoChar('*');
            hide=!hide;
        }
        else
        {
            jButton1.setText("U");
            password.setEchoChar((char)0);
            hide=!hide;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
